name: helm-template-testing
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # pull in policy from conftest repo
    - uses: actions/checkout@master
      with:
        repository: 'open-policy-agent/library'
        ref: 'master'
        path: 'kubernetes'

    - name: Create results directory
      run: mkdir helm-template-result

    - name: Fetch minecraft helm chart
      run: |
        helm repo add itzg https://itzg.github.io/minecraft-server-charts/
        helm pull itzg/minecraft --untar --untardir charts
    
    - name: Generate helm template for minecraft charts
      run: helm template charts/minecraft > helm-template-result/deployment.yaml

  TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Install conftest plugin for helm
        run: helm plugin install https://github.com/instrumenta/helm-conftest

      - name: Execute conftest test on helm template output
        run: helm conftest helm-template-result --policy kubernetes --output table
