name: helm-template-testing

on:
  # Trigger the workflow on push or pull request for below branches
  push:
    branches:
      - main
      - develop
      - feature/*

  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  BUILD-TEST:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # pull in policy from conftest repo
    - uses: actions/checkout@master
      with:
        repository: 'open-policy-agent/library'
        ref: 'master'
        path: 'kubernetes'

    - name: Create results directory
      run: mkdir helm-template-result

    - name: Fetch minecraft helm chart
      run: |
        helm repo add itzg https://itzg.github.io/minecraft-server-charts/
        helm pull itzg/minecraft --untar --untardir charts

    - name: Generate helm template for minecraft charts
      run: helm template charts/minecraft > helm-template-result/deployment.yaml

    - name: Install conftest
      run: |
        brew tap instrumenta/instrumenta
        brew install conftest

    - name: Evaluate deployment using policies
      run: conftest test helm-template-result --policy kubernetes --output table --all-namespaces
